// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzrudezrrthtkmevnwzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6cnVkZXpycnRodGttZXZud3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzIxOTgsImV4cCI6MjA2MDIwODE5OH0.buhVAQKoaiI1xB_Yv07DaaA4ZsDygvZJr9-eRqUi3AA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);